import Dashboard from "@/features/neuclasspage/Dashboard/Dashboard";
import DashboardMain from "@/features/neuclasspage/Dashboard/DashboardMain";
import Head from "next/head";

const Notepad = () => {
  return (
    <>
      <Head>
        <title>Neutrix | Notepad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Dashboard>
        <DashboardMain component="Notepad" />
      </Dashboard>
    </>
  );
};

export default Notepad;
