import BlogList from "@/features/blogpage/blogList/BlogList";
import Hero from "@/features/blogpage/hero/Hero";
import Footer from "@/features/homepage/footer/Footer";
import Head from "next/head";
export default function Blog() {
  return (
    <>
      <Head>
        <title>Our Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Hero />
      <BlogList />
      <Footer />
    </>
  );
}
