import dynamic from "next/dynamic";
import Head from "next/head";

const Hero = dynamic(() => import("@/features/blogpage/hero/Hero"));
const Footer = dynamic(() => import("@/features/homepage/footer/Footer"));
const BlogList = dynamic(() => import("@/features/blogpage/blogList/BlogList"));

export default function Blog() {
  return (
    <>
      <Head>
        <title>Our Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Hero />
      <BlogList />
      <Footer />
    </>
  );
}
