import Head from "next/head";
import Hero from "@/features/hero/Hero";
import About from "@/features/about/About";
import Courses from "@/features/courses/Courses";
import Blog from "@/features/blog/Blog";
import Testimonial from "@/features/testimonial/Testimonial";
import FAQ from "@/features/faq/FAQ";
import Footer from "@/features/footer/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Neutrix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Hero />
      <About />
      <Courses />
      <Blog />
      <Testimonial />
      <FAQ />
      <Footer />
    </>
  );
}
