import Head from "next/head";
import { useState } from "react";
import dynamic from "next/dynamic";
import Navbar from "@/components/navbar/Navbar";

// Dyanmic imports
const Hero = dynamic(() => import("@/features/homepage/hero/Hero"));
const About = dynamic(() => import("@/features/homepage/about/About"));
const Courses = dynamic(() => import("@/features/homepage/courses/Courses"));
const Blog = dynamic(() => import("@/features/homepage/blog/Blog"));
const Testimonial = dynamic(
  () => import("@/features/homepage/testimonial/Testimonial")
);
const FAQ = dynamic(() => import("@/features/homepage/faq/FAQ"));
const Footer = dynamic(() => import("@/features/homepage/footer/Footer"));
const Syllabus = dynamic(() => import("@/features/homepage/courses/Syllabus"));
const BottomNav = dynamic(() => import("@/components/navbar/BottomNav"));

export default function Home() {
  const [openModal, setOpenModal] = useState(false);
  const [syllabusId, setSyllabusId] = useState(0);

  function updateSyllabusId(id: number) {
    setSyllabusId(id);
  }

  return (
    <>
      <Head>
        <title>Neutrix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar />

      <BottomNav />
      <Hero />
      <About />
      <Courses
        updateModal={() => setOpenModal(!openModal)}
        updateId={updateSyllabusId}
      />
      <Blog />
      <Testimonial />
      <FAQ />
      <Footer />
      <Syllabus
        open={openModal}
        updateModal={() => setOpenModal(!openModal)}
        syllabus={syllabusId}
      />
    </>
  );
}
